name: Go Package Workflow
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  ci-workflow:
    name: ci-workflow
    runs-on: ubuntu-latest
    steps:
      - run: ../templates/.github/workflows/go-test.yml
      - run: ../templates/.github/workflows/go-lint.yml
      - run: ../templates/.github/workflows/codeql.yml
